// Demo mode configuration — only active for the demo user
export const DEMO_USER_EMAIL = 'brianvg1206@gmail.com';

export const isDemoUser = (email?: string | null) => email === DEMO_USER_EMAIL;

// --- Brand ---
export const DEMO_BRAND = {
  id: 'demo-brand-001',
  name: 'NovaSkin Colombia',
  industry: 'Belleza & Skincare',
  logo_url: null,
  description: 'Marca de cuidado de la piel 100% colombiana. Productos naturales con ingredientes del Amazonas.',
  website: 'https://novaskin.co',
  city: 'Medellín',
  founded: '2023',
};

// --- Campaigns ---
export const DEMO_CAMPAIGNS = [
  {
    id: 'demo-camp-001',
    title: 'Lanzamiento Serum Vitamina C',
    description: 'Campaña de lanzamiento para nuestro nuevo Serum con Vitamina C y Niacinamida. Buscamos creators de skincare auténticos que muestren resultados reales.',
    status: 'active',
    budget: 8000000,
    currency: 'COP',
    content_type: 'UGC Video',
    deliverables: 3,
    duration_days: 30,
    category: 'Skincare',
    applications: 12,
    approved: 4,
    pending_review: 3,
    completed: 1,
    start_date: '2026-05-01',
    end_date: '2026-05-31',
    thumbnail: null,
    tags: ['skincare', 'vitamina-c', 'ugc', 'colombia'],
  },
  {
    id: 'demo-camp-002',
    title: 'Rutina de Noche - Hidratante Pro',
    description: 'Muestra tu rutina nocturna usando nuestro Hidratante Pro. Formato: before/after de 15-30 seg para Reels e Instagram Stories.',
    status: 'active',
    budget: 4500000,
    currency: 'COP',
    content_type: 'UGC Reels',
    deliverables: 2,
    duration_days: 21,
    category: 'Rutina',
    applications: 8,
    approved: 3,
    pending_review: 2,
    completed: 3,
    start_date: '2026-04-20',
    end_date: '2026-05-20',
    thumbnail: null,
    tags: ['rutina', 'noche', 'hidratacion', 'before-after'],
  },
  {
    id: 'demo-camp-003',
    title: 'Protector Solar SPF 50 - Verano',
    description: 'Contenido veraniego mostrando el protector solar en exteriores. Lifestyle, playa o piscina. Tono: fresco, juvenil, auténtico.',
    status: 'draft',
    budget: 6000000,
    currency: 'COP',
    content_type: 'UGC Video + Foto',
    deliverables: 4,
    duration_days: 45,
    category: 'Lifestyle',
    applications: 0,
    approved: 0,
    pending_review: 0,
    completed: 0,
    start_date: '2026-06-01',
    end_date: '2026-07-15',
    thumbnail: null,
    tags: ['protector-solar', 'verano', 'lifestyle', 'outdoor'],
  },
];

// --- Creators for marketplace ---
export const DEMO_CREATORS = [
  {
    id: 'demo-creator-001',
    full_name: 'Valentina Ríos',
    username: 'valeria.rios',
    avatar_url: null,
    bio: 'Creator de skincare y bienestar 🌿 | Medellín | +80K seguidores | Reels auténticos con resultados reales',
    city: 'Medellín',
    country: 'Colombia',
    followers: 82400,
    engagement_rate: 4.8,
    specialties: ['Skincare', 'Bienestar', 'Lifestyle'],
    platforms: ['Instagram', 'TikTok'],
    rate_per_video: 350000,
    currency: 'COP',
    rating: 4.9,
    reviews: 24,
    verified: true,
    campaigns_completed: 18,
    badge: 'gold',
  },
  {
    id: 'demo-creator-002',
    full_name: 'Juliana Martínez',
    username: 'juli.beauty',
    avatar_url: null,
    bio: 'Makeup & skincare enthusiast 💄 | Bogotá | Tutoriales honestos sin filtros | 45K seguidores',
    city: 'Bogotá',
    country: 'Colombia',
    followers: 45200,
    engagement_rate: 6.2,
    specialties: ['Maquillaje', 'Skincare', 'Tutoriales'],
    platforms: ['Instagram', 'YouTube'],
    rate_per_video: 220000,
    currency: 'COP',
    rating: 4.7,
    reviews: 11,
    verified: true,
    campaigns_completed: 9,
    badge: 'silver',
  },
  {
    id: 'demo-creator-003',
    full_name: 'Sebastián Ospina',
    username: 'seba.ugc',
    avatar_url: null,
    bio: 'UGC creator profesional 📹 | Cali | Especialista en productos de cuidado personal y hogar',
    city: 'Cali',
    country: 'Colombia',
    followers: 28700,
    engagement_rate: 5.1,
    specialties: ['UGC', 'Cuidado Personal', 'Hogar'],
    platforms: ['TikTok', 'Instagram'],
    rate_per_video: 180000,
    currency: 'COP',
    rating: 4.8,
    reviews: 31,
    verified: true,
    campaigns_completed: 27,
    badge: 'gold',
  },
  {
    id: 'demo-creator-004',
    full_name: 'Camila Torres',
    username: 'cami.wellness',
    avatar_url: null,
    bio: 'Wellness & skincare | Barranquilla | Autenticidad ante todo 🌊 | 62K seguidores fieles',
    city: 'Barranquilla',
    country: 'Colombia',
    followers: 62100,
    engagement_rate: 3.9,
    specialties: ['Wellness', 'Skincare', 'Fitness'],
    platforms: ['Instagram', 'TikTok'],
    rate_per_video: 290000,
    currency: 'COP',
    rating: 4.6,
    reviews: 15,
    verified: false,
    campaigns_completed: 12,
    badge: 'silver',
  },
  {
    id: 'demo-creator-005',
    full_name: 'Andrés Felipe Gómez',
    username: 'andres.creates',
    avatar_url: null,
    bio: 'Creator masculino de grooming & skincare 🧴 | Bogotá | Contenido fresco para audiencia 25-35',
    city: 'Bogotá',
    country: 'Colombia',
    followers: 38500,
    engagement_rate: 7.3,
    specialties: ['Grooming', 'Skincare Masculino', 'Lifestyle'],
    platforms: ['TikTok', 'Instagram'],
    rate_per_video: 200000,
    currency: 'COP',
    rating: 4.9,
    reviews: 8,
    verified: true,
    campaigns_completed: 6,
    badge: 'bronze',
  },
  {
    id: 'demo-creator-006',
    full_name: 'Mariana Duque',
    username: 'mari.duque',
    avatar_url: null,
    bio: 'Mamá bloguera 👶 | Skin care seguro para toda la familia | Pereira | 93K seguidores',
    city: 'Pereira',
    country: 'Colombia',
    followers: 93000,
    engagement_rate: 4.1,
    specialties: ['Familia', 'Skincare Seguro', 'Maternidad'],
    platforms: ['Instagram', 'Facebook'],
    rate_per_video: 420000,
    currency: 'COP',
    rating: 4.8,
    reviews: 39,
    verified: true,
    campaigns_completed: 34,
    badge: 'gold',
  },
];

// --- Videos pendientes de revisión ---
export const DEMO_VIDEOS = [
  {
    id: 'demo-video-001',
    campaign_id: 'demo-camp-001',
    campaign_title: 'Lanzamiento Serum Vitamina C',
    creator_name: 'Valentina Ríos',
    creator_username: 'valeria.rios',
    title: 'Serum Vitamina C - Rutina mañana ☀️',
    status: 'pending_review',
    submitted_at: '2026-05-05T14:30:00Z',
    duration_sec: 28,
    platform: 'Instagram Reels',
    video_url: null,
    thumbnail_url: null,
    notes: 'Video grabado con ring light, incluye before/after de 7 días de uso',
  },
  {
    id: 'demo-video-002',
    campaign_id: 'demo-camp-001',
    campaign_title: 'Lanzamiento Serum Vitamina C',
    creator_name: 'Sebastián Ospina',
    creator_username: 'seba.ugc',
    title: 'Review honesta del Serum ✨',
    status: 'pending_review',
    submitted_at: '2026-05-06T09:15:00Z',
    duration_sec: 45,
    platform: 'TikTok',
    video_url: null,
    thumbnail_url: null,
    notes: 'Incluye unboxing + aplicación + opinión tras 3 días. Excelente calidad.',
  },
  {
    id: 'demo-video-003',
    campaign_id: 'demo-camp-002',
    campaign_title: 'Rutina de Noche - Hidratante Pro',
    creator_name: 'Juliana Martínez',
    creator_username: 'juli.beauty',
    title: 'Mi rutina de noche con NovaSkin 🌙',
    status: 'approved',
    submitted_at: '2026-04-28T20:00:00Z',
    duration_sec: 32,
    platform: 'Instagram Reels',
    video_url: null,
    thumbnail_url: null,
    notes: 'Aprobado — excelente presentación del producto, tono natural y auténtico',
  },
  {
    id: 'demo-video-004',
    campaign_id: 'demo-camp-002',
    campaign_title: 'Rutina de Noche - Hidratante Pro',
    creator_name: 'Camila Torres',
    creator_username: 'cami.wellness',
    title: 'Antes y después con el Hidratante Pro',
    status: 'revision_requested',
    submitted_at: '2026-04-30T16:45:00Z',
    duration_sec: 22,
    platform: 'TikTok',
    video_url: null,
    thumbnail_url: null,
    notes: 'Solicitar ajuste: agregar más close-up del producto y mencionar el nombre de la marca al inicio',
  },
];

// --- Dashboard stats ---
export const DEMO_STATS = {
  campaigns_active: 2,
  campaigns_draft: 1,
  videos_pending_review: 2,
  videos_approved: 3,
  videos_total: 7,
  creators_hired: 6,
  total_invested: 12500000,
  currency: 'COP',
  avg_engagement: 5.1,
  content_approval_rate: 78,
};

// --- Tour steps for the guided demo ---
export const DEMO_TOUR_STEPS = [
  {
    id: 'welcome',
    title: 'Bienvenido al Dashboard de Marca',
    description: 'Desde aquí gestionas todas tus campañas de contenido UGC. Ve el estado en tiempo real de tus videos, creadores y presupuesto.',
    target: 'demo-tour-overview',
    position: 'bottom' as const,
  },
  {
    id: 'campaigns',
    title: 'Tus Campañas Activas',
    description: 'Crea briefs de campaña, define el presupuesto y los entregables. Los creadores del marketplace aplican directamente aquí.',
    target: 'demo-tour-campaigns',
    position: 'bottom' as const,
  },
  {
    id: 'videos',
    title: 'Revisión de Contenido',
    description: 'Recibe videos de tus creadores, apruébalos o pide revisiones directamente desde la plataforma. Sin correos ni WhatsApps.',
    target: 'demo-tour-videos',
    position: 'top' as const,
  },
  {
    id: 'marketplace',
    title: 'Encuentra Creadores Perfectos',
    description: 'Busca y filtra entre cientos de creators colombianos verificados. Ve su portafolio, métricas y tarifas antes de contratar.',
    target: 'demo-tour-marketplace',
    position: 'right' as const,
  },
];
