project_id = "hfooshsteglylhvrpuka"

[functions.multi-ai]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true

[functions.content-ai]
verify_jwt = false

[functions.api]
verify_jwt = false

[functions.bunny-webhook]
verify_jwt = false

[functions.notify-drive-upload]
verify_jwt = false

[functions.daily-reminders]
verify_jwt = false

[functions.generate-script]
verify_jwt = false
