import type { PlatformConfig, SocialPlatform } from './types/social.types';

export const PLATFORMS: Record<SocialPlatform, PlatformConfig> = {
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    icon: 'instagram',
    color: '#E4405F',
    bgColor: '#E4405F15',
    maxCaptionLength: 2200,
    supportsVideo: true,
    supportsImage: true,
    supportsCarousel: true,
    supportsStories: true,
    supportsReels: true,
    supportsScheduling: true,
    maxMediaCount: 10,
    maxVideoSizeMB: 650,
    maxImageSizeMB: 8,
    supportedPostTypes: ['post', 'reel', 'story', 'carousel'],
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    icon: 'facebook',
    color: '#1877F2',
    bgColor: '#1877F215',
    maxCaptionLength: 63206,
    supportsVideo: true,
    supportsImage: true,
    supportsCarousel: true,
    supportsStories: true,
    supportsReels: true,
    supportsScheduling: true,
    maxMediaCount: 10,
    maxVideoSizeMB: 4096,
    maxImageSizeMB: 10,
    supportedPostTypes: ['post', 'reel', 'story', 'carousel'],
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    icon: 'tiktok',
    color: '#000000',
    bgColor: '#00000015',
    maxCaptionLength: 2200,
    supportsVideo: true,
    supportsImage: true,
    supportsCarousel: false,
    supportsStories: false,
    supportsReels: false,
    supportsScheduling: true,
    maxMediaCount: 1,
    maxVideoSizeMB: 287,
    maxImageSizeMB: 20,
    supportedPostTypes: ['post'],
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    icon: 'youtube',
    color: '#FF0000',
    bgColor: '#FF000015',
    maxCaptionLength: 5000,
    supportsVideo: true,
    supportsImage: false,
    supportsCarousel: false,
    supportsStories: false,
    supportsReels: false,
    supportsScheduling: true,
    maxMediaCount: 1,
    maxVideoSizeMB: 12288,
    maxImageSizeMB: 0,
    supportedPostTypes: ['post', 'short'],
    comingSoon: true,
  },
  twitter: {
    id: 'twitter',
    name: 'X (Twitter)',
    icon: 'twitter',
    color: '#000000',
    bgColor: '#00000015',
    maxCaptionLength: 280,
    supportsVideo: true,
    supportsImage: true,
    supportsCarousel: false,
    supportsStories: false,
    supportsReels: false,
    supportsScheduling: true,
    maxMediaCount: 4,
    maxVideoSizeMB: 512,
    maxImageSizeMB: 5,
    supportedPostTypes: ['post', 'thread'],
    comingSoon: true,
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: 'linkedin',
    color: '#0A66C2',
    bgColor: '#0A66C215',
    maxCaptionLength: 3000,
    supportsVideo: true,
    supportsImage: true,
    supportsCarousel: true,
    supportsStories: false,
    supportsReels: false,
    supportsScheduling: true,
    maxMediaCount: 9,
    maxVideoSizeMB: 200,
    maxImageSizeMB: 10,
    supportedPostTypes: ['post', 'carousel'],
    comingSoon: true,
  },
  pinterest: {
    id: 'pinterest',
    name: 'Pinterest',
    icon: 'pinterest',
    color: '#BD081C',
    bgColor: '#BD081C15',
    maxCaptionLength: 500,
    supportsVideo: true,
    supportsImage: true,
    supportsCarousel: false,
    supportsStories: false,
    supportsReels: false,
    supportsScheduling: true,
    maxMediaCount: 1,
    maxVideoSizeMB: 2048,
    maxImageSizeMB: 20,
    supportedPostTypes: ['pin'],
    comingSoon: true,
  },
  threads: {
    id: 'threads',
    name: 'Threads',
    icon: 'threads',
    color: '#000000',
    bgColor: '#00000015',
    maxCaptionLength: 500,
    supportsVideo: true,
    supportsImage: true,
    supportsCarousel: true,
    supportsStories: false,
    supportsReels: false,
    supportsScheduling: true,
    maxMediaCount: 10,
    maxVideoSizeMB: 250,
    maxImageSizeMB: 8,
    supportedPostTypes: ['post', 'carousel'],
    comingSoon: true,
  },
};

export const PLATFORM_LIST = Object.values(PLATFORMS);

export const PLATFORM_COLORS: Record<SocialPlatform, string> = {
  instagram: '#E4405F',
  facebook: '#1877F2',
  tiktok: '#69C9D0',
  youtube: '#FF0000',
  twitter: '#1DA1F2',
  linkedin: '#0A66C2',
  pinterest: '#BD081C',
  threads: '#000000',
};

export const POST_STATUS_LABELS: Record<string, string> = {
  draft: 'Borrador',
  scheduled: 'Programado',
  publishing: 'Publicando...',
  published: 'Publicado',
  partially_published: 'Parcial',
  failed: 'Fallido',
  cancelled: 'Cancelado',
};

export const POST_STATUS_COLORS: Record<string, string> = {
  draft: 'bg-gray-500/20 text-gray-400',
  scheduled: 'bg-blue-500/20 text-blue-400',
  publishing: 'bg-yellow-500/20 text-yellow-400',
  published: 'bg-green-500/20 text-green-400',
  partially_published: 'bg-orange-500/20 text-orange-400',
  failed: 'bg-red-500/20 text-red-400',
  cancelled: 'bg-gray-500/20 text-gray-500',
};
