// src/types/client-dna.ts

// ── Emotional Analysis (from Gemini audio analysis) ───────────────────

export interface EmotionalAnalysis {
  // Estado emocional general
  overall_mood: 'enthusiastic' | 'confident' | 'uncertain' | 'stressed' | 'calm' | 'passionate';
  confidence_level: number; // 0-100

  // Emociones detectadas por segmento
  emotional_segments: {
    question_number: number;
    emotion: string;
    intensity: 'low' | 'medium' | 'high';
    notes: string;
  }[];

  // Patrones de comunicacion
  communication_style: {
    pace: 'slow' | 'moderate' | 'fast';
    clarity: 'very_clear' | 'clear' | 'somewhat_unclear';
    energy: 'low' | 'moderate' | 'high';
  };

  // Insights adicionales
  notable_hesitations: string[];
  passion_topics: string[];
  concern_areas: string[];

  // Recomendaciones para el contenido
  content_recommendations: {
    suggested_tone: string;
    avoid_topics: string[];
    emphasize_topics: string[];
  };
}

// ── Audience Location (re-exported from canonical source) ─────────────

export type { AudienceLocation } from '@/lib/locations-data';

// ── DNA Data (strategic profile generated by Perplexity/Gemini) ───────

export interface BusinessIdentity {
  name: string;
  industry: string;
  sub_industry: string;
  description: string;
  business_model: string;
  years_in_market: string;
  competitive_landscape: string;
  origin_story: string;
  mission: string;
  unique_factor: string;
}

export interface ValueProposition {
  main_usp: string;
  differentiators: string[];
  proof_points: string[];
  brand_promise: string;
  main_problem_solved: string;
  solution_description: string;
  key_benefits: string[];
  transformation_promise: string;
}

export interface IdealCustomer {
  demographic: {
    age_range: string;
    gender: string;
    location: string;
    income_level: string;
    occupation: string;
  };
  psychographic: {
    values: string[];
    interests: string[];
    personality_traits: string[];
    lifestyle: string;
  };
  pain_points: string[];
  desires: string[];
  objections: string[];
  buying_triggers: string[];
}

export interface FlagshipOffer {
  name: string;
  description: string;
  price_range: string;
  main_benefit: string;
  funnel_role: string;
  price: string;
  price_justification: string;
  included_features: string[];
  guarantees: string[];
  urgency_elements: string[];
}

export interface BrandIdentity {
  brand_archetype: string;
  personality_traits: string[];
  // New flat fields
  tone_of_voice: string;
  communication_style: string;
  tagline_suggestions: string[];
  key_messages: string[];
  // Old nested fields (backward compat)
  voice: {
    tone: string[];
    do_say: string[];
    dont_say: string[];
  };
  messaging: {
    tagline: string;
    elevator_pitch: string;
    key_messages: string[];
  };
}

export interface VisualIdentity {
  // New fields
  primary_colors: string[];
  secondary_colors: string[];
  color_psychology: string;
  typography_style: string;
  imagery_style: string;
  mood_keywords: string[];
  // Old fields (backward compat)
  brand_colors: string[];
  color_meaning: string;
  visual_style: string[];
  content_themes: string[];
  photography_style: string;
  mood: string;
}

export interface ContentPillar {
  name: string;
  description: string;
  content_ideas: string[];
}

export interface Platform {
  name: string;
  priority: 'high' | 'medium' | 'low';
  strategy: string;
  content_types: string[];
}

export interface MarketingStrategy {
  // New structured fields
  content_pillars: ContentPillar[];
  recommended_platforms: Platform[];
  content_formats: string[];
  posting_frequency: string;
  engagement_tactics: string[];
  hashtag_strategy: string[];
  // Old flat fields (backward compat)
  primary_objective: string;
  secondary_objectives: string[];
  main_cta: string;
  channels: string[];
  monthly_budget: string;
  funnel_strategy: string;
}

export interface AdCopyAngle {
  angle_name: string;
  headline: string;
  body: string;
  cta: string;
}

export interface AdsTargeting {
  // New structured fields
  meta_targeting: {
    interests: string[];
    behaviors: string[];
    demographics: string[];
    lookalike_suggestions: string[];
  };
  google_targeting: {
    keywords: string[];
    audiences: string[];
    placements: string[];
  };
  tiktok_targeting: {
    interests: string[];
    behaviors: string[];
    creators_to_follow: string[];
  };
  hook_suggestions: string[];
  ad_copy_angles: AdCopyAngle[];
  // Old flat fields (backward compat)
  interests: string[];
  behaviors: string[];
  lookalike_sources: string[];
  keywords_google: string[];
  hashtags: string[];
  negative_keywords: string[];
}

export interface DNAData {
  business_identity: BusinessIdentity;
  value_proposition: ValueProposition;
  ideal_customer: IdealCustomer;
  flagship_offer: FlagshipOffer;
  brand_identity: BrandIdentity;
  visual_identity: VisualIdentity;
  marketing_strategy: MarketingStrategy;
  ads_targeting: AdsTargeting;
}

// ── Client DNA record ─────────────────────────────────────────────────

export interface ClientDNA {
  id: string;
  client_id: string;
  transcription: string | null;
  emotional_analysis: EmotionalAnalysis;
  audience_locations: AudienceLocation[];
  dna_data: DNAData | null;
  version: number;
  status: 'processing' | 'completed' | 'error';
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
