// src/config/service-catalog.ts

import {
  Video, Camera, Layout, Image, Radio, Mic, FileText, Headphones,
  Users, Palette, Scissors, Sparkles, Frame, Music, Paintbrush,
  Clapperboard, Film, TrendingUp, Share2, MessageCircle, Target,
  DollarSign, Search, Mail, Rocket, Database, BarChart3,
  Globe, Smartphone, Bot, GraduationCap, BookOpen, HelpCircle, Star,
} from 'lucide-react';
import type { ServiceGroup, ServiceType } from '@/types/product-dna';
import type { WizardQuestion } from '@/config/wizard-questions';

export interface ServiceConfig {
  id: ServiceType;
  name: string;
  description: string;
  icon: React.ElementType;
  color: string;
  gradient: string;
  questions: WizardQuestion[];
  estimatedTime: string;
  complexity: 'simple' | 'moderate' | 'complex';
}

export interface ServiceGroupConfig {
  id: ServiceGroup;
  name: string;
  description: string;
  icon: React.ElementType;
  color: string;
  gradient: string;
  services: ServiceConfig[];
}

export const SERVICE_GROUPS: ServiceGroupConfig[] = [
  {
    id: 'content_creation',
    name: 'Creación de Contenido',
    description: 'Videos, fotos y contenido original para tu marca',
    icon: Video,
    color: 'purple',
    gradient: 'from-purple-500 to-pink-500',
    services: [
      {
        id: 'video_ugc',
        name: 'Video UGC',
        description: 'Videos auténticos estilo usuario para redes sociales',
        icon: Video,
        color: 'purple',
        gradient: 'from-purple-500 to-violet-500',
        complexity: 'moderate',
        estimatedTime: '3-5 días',
        questions: [],
      },
      {
        id: 'photo_ugc',
        name: 'Foto UGC',
        description: 'Fotografías naturales y auténticas del producto',
        icon: Camera,
        color: 'pink',
        gradient: 'from-pink-500 to-rose-500',
        complexity: 'simple',
        estimatedTime: '2-3 días',
        questions: [],
      },
      {
        id: 'carousel_ugc',
        name: 'Carrusel UGC',
        description: 'Carruseles de imágenes para Instagram/Facebook',
        icon: Layout,
        color: 'rose',
        gradient: 'from-rose-500 to-orange-500',
        complexity: 'moderate',
        estimatedTime: '3-4 días',
        questions: [],
      },
      {
        id: 'photography',
        name: 'Fotografía Profesional',
        description: 'Sesiones fotográficas de producto o lifestyle',
        icon: Image,
        color: 'amber',
        gradient: 'from-amber-500 to-yellow-500',
        complexity: 'moderate',
        estimatedTime: '5-7 días',
        questions: [],
      },
      {
        id: 'live_streaming',
        name: 'Live Streaming',
        description: 'Transmisiones en vivo para ventas o engagement',
        icon: Radio,
        color: 'red',
        gradient: 'from-red-500 to-pink-500',
        complexity: 'complex',
        estimatedTime: 'Por definir',
        questions: [],
      },
      {
        id: 'voice_over',
        name: 'Locución',
        description: 'Voces profesionales para videos y anuncios',
        icon: Mic,
        color: 'blue',
        gradient: 'from-blue-500 to-cyan-500',
        complexity: 'simple',
        estimatedTime: '1-2 días',
        questions: [],
      },
      {
        id: 'scriptwriting',
        name: 'Guionismo',
        description: 'Guiones creativos para videos y campañas',
        icon: FileText,
        color: 'indigo',
        gradient: 'from-indigo-500 to-purple-500',
        complexity: 'moderate',
        estimatedTime: '2-4 días',
        questions: [],
      },
      {
        id: 'podcast_production',
        name: 'Producción de Podcast',
        description: 'Grabación y producción de episodios',
        icon: Headphones,
        color: 'emerald',
        gradient: 'from-emerald-500 to-teal-500',
        complexity: 'complex',
        estimatedTime: '5-10 días',
        questions: [],
      },
      {
        id: 'influencer_post',
        name: 'Post de Influencer',
        description: 'Contenido patrocinado con influencers',
        icon: Users,
        color: 'fuchsia',
        gradient: 'from-fuchsia-500 to-pink-500',
        complexity: 'moderate',
        estimatedTime: '7-14 días',
        questions: [],
      },
      {
        id: 'graphic_design',
        name: 'Diseño Gráfico',
        description: 'Piezas visuales para redes y campañas',
        icon: Palette,
        color: 'cyan',
        gradient: 'from-cyan-500 to-blue-500',
        complexity: 'moderate',
        estimatedTime: '3-5 días',
        questions: [],
      },
    ],
  },
  {
    id: 'post_production',
    name: 'Post-Producción',
    description: 'Edición, efectos y acabados profesionales',
    icon: Scissors,
    color: 'blue',
    gradient: 'from-blue-500 to-indigo-500',
    services: [
      {
        id: 'video_editing',
        name: 'Edición de Video',
        description: 'Corte, montaje y edición profesional',
        icon: Scissors,
        color: 'blue',
        gradient: 'from-blue-500 to-indigo-500',
        complexity: 'moderate',
        estimatedTime: '3-7 días',
        questions: [],
      },
      {
        id: 'motion_graphics',
        name: 'Motion Graphics',
        description: 'Animaciones y gráficos en movimiento',
        icon: Sparkles,
        color: 'violet',
        gradient: 'from-violet-500 to-purple-500',
        complexity: 'complex',
        estimatedTime: '5-10 días',
        questions: [],
      },
      {
        id: 'thumbnail_design',
        name: 'Diseño de Thumbnails',
        description: 'Miniaturas atractivas para YouTube/videos',
        icon: Frame,
        color: 'red',
        gradient: 'from-red-500 to-orange-500',
        complexity: 'simple',
        estimatedTime: '1-2 días',
        questions: [],
      },
      {
        id: 'sound_design',
        name: 'Diseño de Sonido',
        description: 'Audio, música y efectos sonoros',
        icon: Music,
        color: 'emerald',
        gradient: 'from-emerald-500 to-green-500',
        complexity: 'moderate',
        estimatedTime: '3-5 días',
        questions: [],
      },
      {
        id: 'color_grading',
        name: 'Colorización',
        description: 'Corrección y gradación de color profesional',
        icon: Paintbrush,
        color: 'amber',
        gradient: 'from-amber-500 to-orange-500',
        complexity: 'moderate',
        estimatedTime: '2-4 días',
        questions: [],
      },
      {
        id: 'animation_2d_3d',
        name: 'Animación 2D/3D',
        description: 'Animaciones y renders profesionales',
        icon: Clapperboard,
        color: 'pink',
        gradient: 'from-pink-500 to-rose-500',
        complexity: 'complex',
        estimatedTime: '10-20 días',
        questions: [],
      },
      {
        id: 'creative_direction',
        name: 'Dirección Creativa',
        description: 'Liderazgo y visión artística de proyectos',
        icon: Star,
        color: 'yellow',
        gradient: 'from-yellow-500 to-amber-500',
        complexity: 'complex',
        estimatedTime: 'Continuo',
        questions: [],
      },
      {
        id: 'audiovisual_production',
        name: 'Producción Audiovisual',
        description: 'Producción completa de contenido AV',
        icon: Film,
        color: 'indigo',
        gradient: 'from-indigo-500 to-blue-500',
        complexity: 'complex',
        estimatedTime: '15-30 días',
        questions: [],
      },
    ],
  },
  {
    id: 'strategy_marketing',
    name: 'Estrategia & Marketing',
    description: 'Planificación estratégica y crecimiento digital',
    icon: TrendingUp,
    color: 'emerald',
    gradient: 'from-emerald-500 to-teal-500',
    services: [
      {
        id: 'social_media_management',
        name: 'Gestión de Redes',
        description: 'Administración completa de redes sociales',
        icon: Share2,
        color: 'blue',
        gradient: 'from-blue-500 to-cyan-500',
        complexity: 'moderate',
        estimatedTime: 'Mensual',
        questions: [],
      },
      {
        id: 'content_strategy',
        name: 'Estrategia de Contenido',
        description: 'Planificación y calendario de contenidos',
        icon: Layout,
        color: 'purple',
        gradient: 'from-purple-500 to-violet-500',
        complexity: 'moderate',
        estimatedTime: '7-14 días',
        questions: [],
      },
      {
        id: 'community_management',
        name: 'Community Management',
        description: 'Gestión y engagement de comunidad',
        icon: MessageCircle,
        color: 'pink',
        gradient: 'from-pink-500 to-rose-500',
        complexity: 'moderate',
        estimatedTime: 'Continuo',
        questions: [],
      },
      {
        id: 'digital_strategy',
        name: 'Estrategia Digital',
        description: 'Plan integral de presencia digital',
        icon: Target,
        color: 'emerald',
        gradient: 'from-emerald-500 to-green-500',
        complexity: 'complex',
        estimatedTime: '10-15 días',
        questions: [],
      },
      {
        id: 'media_buying',
        name: 'Pauta Digital / Media Buying',
        description: 'Gestión de campañas publicitarias',
        icon: DollarSign,
        color: 'amber',
        gradient: 'from-amber-500 to-yellow-500',
        complexity: 'complex',
        estimatedTime: 'Continuo',
        questions: [],
      },
      {
        id: 'seo_sem',
        name: 'SEO / SEM',
        description: 'Posicionamiento en buscadores',
        icon: Search,
        color: 'orange',
        gradient: 'from-orange-500 to-red-500',
        complexity: 'complex',
        estimatedTime: '30-90 días',
        questions: [],
      },
      {
        id: 'email_marketing',
        name: 'Email Marketing',
        description: 'Campañas de email y automatización',
        icon: Mail,
        color: 'red',
        gradient: 'from-red-500 to-pink-500',
        complexity: 'moderate',
        estimatedTime: '5-10 días',
        questions: [],
      },
      {
        id: 'growth_hacking',
        name: 'Growth Hacking',
        description: 'Estrategias de crecimiento acelerado',
        icon: Rocket,
        color: 'violet',
        gradient: 'from-violet-500 to-purple-500',
        complexity: 'complex',
        estimatedTime: 'Continuo',
        questions: [],
      },
      {
        id: 'crm_management',
        name: 'Gestión CRM',
        description: 'Gestión de relaciones con clientes',
        icon: Database,
        color: 'indigo',
        gradient: 'from-indigo-500 to-blue-500',
        complexity: 'complex',
        estimatedTime: '15-30 días',
        questions: [],
      },
      {
        id: 'cro',
        name: 'Optimización de Conversión',
        description: 'CRO y mejora de tasas de conversión',
        icon: BarChart3,
        color: 'teal',
        gradient: 'from-teal-500 to-cyan-500',
        complexity: 'complex',
        estimatedTime: '30-60 días',
        questions: [],
      },
    ],
  },
  {
    id: 'technology',
    name: 'Tecnología',
    description: 'Desarrollo y soluciones tecnológicas',
    icon: Globe,
    color: 'cyan',
    gradient: 'from-cyan-500 to-blue-500',
    services: [
      {
        id: 'web_development',
        name: 'Desarrollo Web',
        description: 'Sitios web y landing pages',
        icon: Globe,
        color: 'blue',
        gradient: 'from-blue-500 to-indigo-500',
        complexity: 'complex',
        estimatedTime: '15-45 días',
        questions: [],
      },
      {
        id: 'app_development',
        name: 'Desarrollo de Apps',
        description: 'Aplicaciones móviles iOS/Android',
        icon: Smartphone,
        color: 'purple',
        gradient: 'from-purple-500 to-pink-500',
        complexity: 'complex',
        estimatedTime: '60-120 días',
        questions: [],
      },
      {
        id: 'ai_automation',
        name: 'IA y Automatización',
        description: 'Soluciones con inteligencia artificial',
        icon: Bot,
        color: 'emerald',
        gradient: 'from-emerald-500 to-teal-500',
        complexity: 'complex',
        estimatedTime: '30-90 días',
        questions: [],
      },
    ],
  },
  {
    id: 'education_training',
    name: 'Educación',
    description: 'Formación y capacitación profesional',
    icon: GraduationCap,
    color: 'amber',
    gradient: 'from-amber-500 to-orange-500',
    services: [
      {
        id: 'online_courses',
        name: 'Cursos Online',
        description: 'Creación de cursos digitales',
        icon: GraduationCap,
        color: 'amber',
        gradient: 'from-amber-500 to-yellow-500',
        complexity: 'complex',
        estimatedTime: '30-60 días',
        questions: [],
      },
      {
        id: 'workshops',
        name: 'Talleres y Capacitaciones',
        description: 'Sesiones de formación en vivo',
        icon: BookOpen,
        color: 'orange',
        gradient: 'from-orange-500 to-red-500',
        complexity: 'moderate',
        estimatedTime: '7-14 días',
        questions: [],
      },
    ],
  },
  {
    id: 'general_services',
    name: 'General',
    description: 'Servicios personalizados y consultoría',
    icon: HelpCircle,
    color: 'gray',
    gradient: 'from-gray-500 to-slate-500',
    services: [
      {
        id: 'consulting',
        name: 'Consultoría',
        description: 'Asesoría estratégica personalizada',
        icon: HelpCircle,
        color: 'indigo',
        gradient: 'from-indigo-500 to-purple-500',
        complexity: 'complex',
        estimatedTime: 'Por definir',
        questions: [],
      },
      {
        id: 'custom',
        name: 'Personalizado',
        description: 'Proyecto a la medida de tus necesidades',
        icon: Star,
        color: 'pink',
        gradient: 'from-pink-500 to-rose-500',
        complexity: 'complex',
        estimatedTime: 'Por definir',
        questions: [],
      },
    ],
  },
];

// Helper para obtener configuración
export function getServiceGroup(groupId: ServiceGroup): ServiceGroupConfig | undefined {
  return SERVICE_GROUPS.find(g => g.id === groupId);
}

export function getService(serviceId: ServiceType): ServiceConfig | undefined {
  for (const group of SERVICE_GROUPS) {
    const service = group.services.find(s => s.id === serviceId);
    if (service) return service;
  }
  return undefined;
}

export function getServicesByGroup(groupId: ServiceGroup): ServiceConfig[] {
  return getServiceGroup(groupId)?.services || [];
}
