import { useState, useCallback, useRef, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import {
  cleanTextForVoice,
  detectVoiceEmotion,
  isSpeakableText,
  type KiroVoiceEmotion,
} from '../utils/textToSpeechUtils';

// ═══════════════════════════════════════════════════════════════════════════
// TIPOS
// ═══════════════════════════════════════════════════════════════════════════

export interface UseKiroVoiceReturn {
  /** KIRO is currently speaking audio */
  isSpeaking: boolean;
  /** Audio is being generated by the API */
  isLoading: boolean;
  /** Whether the browser supports Web Audio API */
  isSupported: boolean;
  /** Speak text aloud. Automatically detects emotion if not provided. */
  speak: (text: string, emotion?: KiroVoiceEmotion) => Promise<void>;
  /** Stop current audio playback immediately */
  stop: () => void;
}

// ═══════════════════════════════════════════════════════════════════════════
// CONSTANTES
// ═══════════════════════════════════════════════════════════════════════════

const MAX_CACHE_ENTRIES = 20;

// ═══════════════════════════════════════════════════════════════════════════
// HOOK
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Hook that manages KIRO's voice output via ElevenLabs TTS.
 *
 * Receives `enabled` and `volume` from the parent (kiroSettings) as the
 * single source of truth — no internal duplication of these states.
 *
 * @param enabled - Whether voice is enabled (from kiroSettings.voiceEnabled)
 * @param volume - Voice volume 0-1 (from kiroSettings.voiceVolume)
 * @param onSpeakStart - Called when KIRO starts speaking (for animation sync)
 * @param onSpeakEnd - Called when KIRO finishes speaking (for animation sync)
 */
export function useKiroVoice(
  enabled: boolean,
  volume: number,
  onSpeakStart?: () => void,
  onSpeakEnd?: () => void,
): UseKiroVoiceReturn {
  // ─── Check browser support ───
  const isSupported = typeof window !== 'undefined' &&
    !!(window.AudioContext || (window as any).webkitAudioContext);

  // ─── State (only for transient playback state) ───
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  // ─── Refs ───
  const audioCtxRef = useRef<AudioContext | null>(null);
  const sourceNodeRef = useRef<AudioBufferSourceNode | null>(null);
  const gainNodeRef = useRef<GainNode | null>(null);
  const cacheRef = useRef<Map<string, AudioBuffer>>(new Map());
  const abortRef = useRef<AbortController | null>(null);
  // Use refs for callbacks to avoid stale closures in audio onended
  const onSpeakStartRef = useRef(onSpeakStart);
  const onSpeakEndRef = useRef(onSpeakEnd);
  onSpeakStartRef.current = onSpeakStart;
  onSpeakEndRef.current = onSpeakEnd;
  // Use ref for volume so playBuffer always has the latest value
  const volumeRef = useRef(volume);
  volumeRef.current = volume;

  // ─── Ensure AudioContext ───
  const getAudioContext = useCallback((): AudioContext | null => {
    if (!isSupported) return null;

    if (!audioCtxRef.current) {
      const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
      audioCtxRef.current = new AudioCtx();
    }
    if (audioCtxRef.current.state === 'suspended') {
      audioCtxRef.current.resume();
    }
    return audioCtxRef.current;
  }, [isSupported]);

  // ─── Stop current playback ───
  const stop = useCallback(() => {
    if (abortRef.current) {
      abortRef.current.abort();
      abortRef.current = null;
    }
    if (sourceNodeRef.current) {
      try {
        sourceNodeRef.current.stop();
      } catch { /* Already stopped */ }
      sourceNodeRef.current.disconnect();
      sourceNodeRef.current = null;
    }
    setIsSpeaking(false);
    setIsLoading(false);
  }, []);

  // Stop playback when voice is disabled
  useEffect(() => {
    if (!enabled && isSpeaking) {
      stop();
    }
  }, [enabled, isSpeaking, stop]);

  // Update gain node when volume changes during playback
  useEffect(() => {
    if (gainNodeRef.current) {
      gainNodeRef.current.gain.value = volume;
    }
  }, [volume]);

  // ─── Play an AudioBuffer ───
  const playBuffer = useCallback(
    (buffer: AudioBuffer) => {
      const ctx = getAudioContext();
      if (!ctx) return;

      // Stop any previous playback
      if (sourceNodeRef.current) {
        try {
          sourceNodeRef.current.stop();
        } catch { /* ignore */ }
        sourceNodeRef.current.disconnect();
      }

      const source = ctx.createBufferSource();
      source.buffer = buffer;

      const gain = ctx.createGain();
      gain.gain.value = volumeRef.current;
      gainNodeRef.current = gain;

      source.connect(gain);
      gain.connect(ctx.destination);

      sourceNodeRef.current = source;

      source.onended = () => {
        setIsSpeaking(false);
        sourceNodeRef.current = null;
        onSpeakEndRef.current?.();
      };

      setIsSpeaking(true);
      onSpeakStartRef.current?.();
      source.start();
    },
    [getAudioContext],
  );

  // ─── Speak text ───
  const speak = useCallback(
    async (text: string, emotion?: KiroVoiceEmotion) => {
      if (!isSupported) return;
      if (!isSpeakableText(text)) return;

      const cleanedText = cleanTextForVoice(text);
      if (cleanedText.length < 5) return;

      const resolvedEmotion = emotion || detectVoiceEmotion(text);
      const cacheKey = `${cleanedText}::${resolvedEmotion}`;

      // Check in-memory cache
      const cached = cacheRef.current.get(cacheKey);
      if (cached) {
        playBuffer(cached);
        return;
      }

      // Cancel any previous request
      stop();

      const controller = new AbortController();
      abortRef.current = controller;

      setIsLoading(true);

      try {
        getAudioContext();

        const { data: sessionData } = await supabase.auth.getSession();
        const token = sessionData?.session?.access_token;

        const functionUrl = `${import.meta.env.VITE_SUPABASE_URL || 'https://wjkbqcrxwsmvtxmqgiqc.supabase.co'}/functions/v1/kiro-voice`;

        const response = await fetch(functionUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            ...(token ? { Authorization: `Bearer ${token}` } : {}),
            apikey: import.meta.env.VITE_SUPABASE_ANON_KEY || '',
          },
          body: JSON.stringify({ text: cleanedText, emotion: resolvedEmotion }),
          signal: controller.signal,
        });

        if (!response.ok) {
          const errorBody = await response.text().catch(() => '');
          console.warn(`[KIRO Voice] API error ${response.status}:`, errorBody);
          setIsLoading(false);
          return;
        }

        const arrayBuffer = await response.arrayBuffer();
        const ctx = getAudioContext();
        if (!ctx) {
          setIsLoading(false);
          return;
        }

        const audioBuffer = await ctx.decodeAudioData(arrayBuffer);

        // Store in cache (evict oldest if full)
        if (cacheRef.current.size >= MAX_CACHE_ENTRIES) {
          const firstKey = cacheRef.current.keys().next().value;
          if (firstKey) cacheRef.current.delete(firstKey);
        }
        cacheRef.current.set(cacheKey, audioBuffer);

        setIsLoading(false);

        if (!controller.signal.aborted) {
          playBuffer(audioBuffer);
        }
      } catch (err: any) {
        if (err?.name === 'AbortError') return;
        console.warn('[KIRO Voice] Speak error:', err);
        setIsLoading(false);
      }
    },
    [isSupported, stop, playBuffer, getAudioContext],
  );

  // ─── Cleanup on unmount ───
  useEffect(() => {
    return () => {
      if (abortRef.current) {
        abortRef.current.abort();
      }
      if (sourceNodeRef.current) {
        try {
          sourceNodeRef.current.stop();
        } catch { /* ignore */ }
      }
    };
  }, []);

  return {
    isSpeaking,
    isLoading,
    isSupported,
    speak,
    stop,
  };
}
