-- Agregar campos faltantes a la tabla content
ALTER TABLE public.content
ADD COLUMN IF NOT EXISTS product TEXT,
ADD COLUMN IF NOT EXISTS campaign_week TEXT,
ADD COLUMN IF NOT EXISTS strategist_id UUID,
ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS invoiced BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS drive_url TEXT,
ADD COLUMN IF NOT EXISTS creator_assigned_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS editor_assigned_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS reference_url TEXT,
ADD COLUMN IF NOT EXISTS creator_paid BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS editor_paid BOOLEAN DEFAULT false;