-- Migration: Auto-create marketplace profiles for ALL existing users
-- + Trigger to auto-create for new users
-- + Fix RLS to allow own profile viewing

-- ============================================
-- 1. Bulk create creator_profiles for ALL remaining users
-- ============================================

INSERT INTO public.creator_profiles (
  user_id,
  display_name,
  slug,
  bio,
  avatar_url,
  location_city,
  location_country,
  categories,
  languages,
  social_links,
  is_available,
  is_active,
  platforms,
  marketplace_roles,
  content_types
)
SELECT
  p.id,
  COALESCE(NULLIF(TRIM(p.full_name), ''), 'Creador'),
  NULL, -- slug auto-generated by trigger
  p.bio,
  p.avatar_url,
  p.city,
  COALESCE(p.country, 'CO'),
  COALESCE(p.content_categories, '{}'::text[]),
  COALESCE(p.languages, '{es}'::text[]),
  jsonb_strip_nulls(jsonb_build_object(
    'instagram', NULLIF(p.instagram, ''),
    'tiktok', NULLIF(p.tiktok, '')
  )),
  true,
  true, -- active by default so they appear in marketplace
  '{}'::text[],
  '{}'::text[],
  '{}'::text[]
FROM public.profiles p
JOIN auth.users u ON u.id = p.id  -- exclude orphaned profiles
WHERE p.id NOT IN (SELECT user_id FROM public.creator_profiles)
ON CONFLICT (user_id) DO NOTHING;

-- ============================================
-- 2. Activate any existing draft profiles
-- ============================================

UPDATE public.creator_profiles
SET is_active = true
WHERE is_active = false;

-- ============================================
-- 3. Trigger: auto-create creator_profile on new user signup
-- ============================================

CREATE OR REPLACE FUNCTION public.auto_create_creator_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.creator_profiles (
    user_id,
    display_name,
    bio,
    avatar_url,
    location_city,
    location_country,
    categories,
    languages,
    social_links,
    is_available,
    is_active,
    platforms,
    marketplace_roles,
    content_types
  )
  VALUES (
    NEW.id,
    COALESCE(NULLIF(TRIM(NEW.full_name), ''), 'Creador'),
    NEW.bio,
    NEW.avatar_url,
    NEW.city,
    COALESCE(NEW.country, 'CO'),
    COALESCE(NEW.content_categories, '{}'::text[]),
    COALESCE(NEW.languages, '{es}'::text[]),
    jsonb_strip_nulls(jsonb_build_object(
      'instagram', NULLIF(NEW.instagram, ''),
      'tiktok', NULLIF(NEW.tiktok, '')
    )),
    true,
    true,
    '{}'::text[],
    '{}'::text[],
    '{}'::text[]
  )
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$;

-- Drop existing trigger if any, then create
DROP TRIGGER IF EXISTS trigger_auto_create_creator_profile ON public.profiles;

CREATE TRIGGER trigger_auto_create_creator_profile
  AFTER INSERT ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_create_creator_profile();

-- ============================================
-- 4. Fix RLS: allow users to see their own profile (even drafts)
-- ============================================

DROP POLICY IF EXISTS "Creator profiles are publicly readable" ON public.creator_profiles;

CREATE POLICY "Creator profiles are publicly readable"
  ON public.creator_profiles FOR SELECT
  USING (
    is_active = true
    OR user_id = auth.uid()
  );

-- ============================================
-- 5. Keep profile data in sync on updates
-- ============================================

CREATE OR REPLACE FUNCTION public.sync_profile_updates_to_marketplace()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.creator_profiles
  SET
    display_name = COALESCE(NULLIF(TRIM(NEW.full_name), ''), display_name),
    avatar_url = COALESCE(NEW.avatar_url, avatar_url),
    location_city = COALESCE(NEW.city, location_city),
    location_country = COALESCE(NEW.country, location_country),
    social_links = jsonb_strip_nulls(
      COALESCE(social_links, '{}'::jsonb)
      || jsonb_build_object(
        'instagram', NULLIF(NEW.instagram, ''),
        'tiktok', NULLIF(NEW.tiktok, '')
      )
    ),
    updated_at = now()
  WHERE user_id = NEW.id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_sync_profile_to_marketplace ON public.profiles;

CREATE TRIGGER trigger_sync_profile_to_marketplace
  AFTER UPDATE ON public.profiles
  FOR EACH ROW
  WHEN (
    OLD.full_name IS DISTINCT FROM NEW.full_name
    OR OLD.avatar_url IS DISTINCT FROM NEW.avatar_url
    OR OLD.city IS DISTINCT FROM NEW.city
    OR OLD.country IS DISTINCT FROM NEW.country
    OR OLD.instagram IS DISTINCT FROM NEW.instagram
    OR OLD.tiktok IS DISTINCT FROM NEW.tiktok
  )
  EXECUTE FUNCTION public.sync_profile_updates_to_marketplace();
